### ISSUE TITLE
Field types -- "Links"

### ISSUE THREAD

**Issue by cj** [datocms/plugins#1]
I would love to create a plugin to solve this issue https://github.com/datocms/feature-requests/issues/100, but in order to do that, I would need `Links` as a "Field types" option.

![](https://cl.ly/a727f619f488/Image%2525202018-10-22%252520at%2525204.06.13%252520PM.png)

**Comment by stefanoverna** [comment]
It seems to me that field type string, or slug, would be more appropriate.. why Links? :/

**Comment by cj** [comment]
@stefanoverna This plugin is to replace a "Links" type so that you can see more information on the linked record than a single "Title field", i.e. concentrate First and Last name, instead of just seeing the First name field, which is no use as lots of people have the same first name.  According to your docs it is a fieldTypes ![](https://cl.ly/7e628df99fd8/Image%2525202018-10-22%252520at%2525205.44.42%252520PM.png).

Is not showing in that dropdown a bug, or are the docs wrong?

**Comment by cj** [comment]
Currently lets say you have two tabels (models) one called `employees` and another called `jobs`.  The `employees` table has `First Name` and `Last Name` columns.  In the jobs table you want to add a `Links` column that points to who the job belongs to, so you would create an `assigned_to` column with a type `Links` and select single `Link`.  With the current behaviour when you go to create a new record in the `jobs` table you will only see the `First Name` field of the `Link` table `employees`, as it only allows you to select a single `Title Field`; which if you have a lot of employees means that people could have the same first name.  As pointed out in slack, someone else has this issue and a work around they have been using to overcome it (which is not ideal) ![](https://cl.ly/72bbda302ecc/Image%2525202018-10-22%252520at%2525206.04.33%252520PM.png)

This is where a plugin would solve this issue, I could now create one that would allow you to override the `Links` field and allow you to select multiple Type fields for the linked record to display instead of one.  The plugin docs has this option as pointed out from my screenshot above, but the dropdown in the create private plugin (shown in my first screenshot) do not have this option, so the plugin won't be available for the `Links` field type.

**Comment by cj** [comment]
This video should makes things a lot clearer https://cl.ly/119bfc49a5e9.

**Comment by cj** [comment]
Not only that once you actually create a record, there is no way to tell which Joe the job is assigned to as you don't see their last name  ![](https://cl.ly/4ff07b0e09de/Image%2525202018-10-22%252520at%2525206.28.59%252520PM.png)

**Comment by stefanoverna** [comment]
Done @cj!

**Comment by cj** [comment]
@stefanoverna awesome!  Thank you so much!  😄

**Comment by cj** [comment]
@stefanoverna quick question, will you be making it possible for the [Plugin SDK](https://www.datocms.com/docs/plugins/sdk-reference/) to access the `Links` field values?

Right now as a work around I'm using a global parameter for a read only api key and then using the standard graphql api query to get the data.
