### ISSUE TITLE
Issue installing plugins

### ISSUE THREAD

**Issue by velomovies** [datocms/plugins#100]
Hi all!

On our translate-fields plugin we got an issue which I only could reproduce when browsing trough plugins. (see https://github.com/voorhoede/datocms-plugin-translate-fields/issues/43)

I think this is already solved because a popup opens where you can add the plugin, but I can imagine this could be opitimised. So to reproduce and check if nothing else is wrong I open this issue.

**How I could reproduce**
In a DatoCMS project on the plugins page
- Click on `+ Add a new plugin`
- Click on `From Marketplace`
- Click on `View all ->` in the "Most popular" section
- Browse by clicking on `Next` or any number of the pagination.

Now the url parameters disappear so it won't install automatically to the right project.

**Comment by marcelofinamorvieira** [comment]
Thank you @velomovies for letting us know!

We just fixed this issue with that last deploy :)
