### ISSUE TITLE
Add a confirmation to the table-editor plugin

### ISSUE THREAD

**Issue by ekyburz** [datocms/plugins#101]
Hi, this is an enhancement request for the table-editor plugin.

I have been using the plugin and have noticed that the clear button directly deletes the entire table without confirmation. This could lead to accidental data loss. My editors have tried to use the button to clear a single row or column and were surprised that it deletes the entire table.

![CleanShot 2024-03-05 at 17 18 59](https://github.com/datocms/plugins/assets/114604643/0c4ba5a2-326f-47be-8ef4-41ab8a9b2062)

So this request would simply add a confirmation message after the button is clicked that informs the user that the entire table would be deleted.

Any help would be appreciated.

Thank you!

**Comment by arcataroger** [comment]
@ekyburz Thank you for the suggestion! That makes sense.

We have a draft PR for this that the devs will review when they can: #102 

PS In the future, though, could you please consider putting enhancement requests in the feature request section of our forum? https://community.datocms.com/c/feature-requests/22

That just helps us route and prioritize them better :) In this case it was a simple enough fix, so no worries.

Thanks again for the report!

**Comment by arcataroger** [comment]
Sorting out some NPM permission issues, but hopefully we'll have this deployed soon! Will let you know.

**Comment by arcataroger** [comment]
The confirmation box is now available in plugin version `0.2.0`!
![image](https://github.com/datocms/plugins/assets/11964962/066496bb-d146-433b-881f-3f29f3a196c5)
