### ISSUE TITLE
Working with non-boolean field types - should I create a new plugin or rather extend this one?

### ISSUE THREAD

**Issue by jakubzet** [datocms/plugins#15]
Hi!
First of all,  thank you for this handy plugin!

The system I am currently working on has a requirement to enable showing certain fields depending on other field values (not only boolean values, as currently here). I noticed, that the current code after some tweaks would allow to achieve such behaviour.

Yet, I'm not sure if I should fork this plugin and submit a new one with very similar codebase allowing such behaviour, or is it good idea to stay with the current plugin and commit a pull request, which would extend it's possibilities.

I'd like to know - straight fro the authors - which solution would be better for further development - thank you in advance! :)

**Comment by matjack1** [comment]
Hello @jakubzet if it's retro-compatible and extends the functionality I think it's worth opening a pull request. Meanwhile you can always use your fork as a private plugin so that you don't need to wait for us :)
