### ISSUE TITLE
[Yandex Translate] Doesn't work within Modular blocks fields

### ISSUE THREAD

**Issue by nephlin7** [datocms/plugins#19]
I've noticed that this plugin doesn't work within modular block fields, is this a bug or should it work like this?

Some screenshots:

![Captura de Pantalla 2020-07-25 a la(s) 11 29 08 a  m](https://user-images.githubusercontent.com/22168189/88462650-43594300-ce6a-11ea-963c-16f6c37fa44a.png)
![Captura de Pantalla 2020-07-25 a la(s) 11 31 21 a  m](https://user-images.githubusercontent.com/22168189/88462668-6a177980-ce6a-11ea-8285-1d9f1ee68076.png)

![Captura de Pantalla 2020-07-25 a la(s) 11 29 49 a  m](https://user-images.githubusercontent.com/22168189/88462653-46543380-ce6a-11ea-9176-a1fb252b09e5.png)
### **_Translate in other languages_** doesn't appear

**Comment by matjack1** [comment]
hey @nephlin7 problem is that the plugin is not meant to work inside modular contents as modular contents can be localized but then inside blocks also the fields can be localised or not. So to avoid confusion and replication of the plugin in unwanted places we disabled that in modular contents.

But, if it makes sense in your case, you can create your own plugin by using ours and removing (or tweaking) this condition here: https://github.com/datocms/plugins/blob/master/yandex-translate/src/index.js#L21 as modular contents will never show as localized this plugin will never show for modular contents.

**Comment by nephlin7** [comment]
@matjack1, thanks for the answer.
