### ISSUE TITLE
Conditional fields plugin: target field(s) with localization enabled are always shown

### ISSUE THREAD

**Issue by Samuel-L** [datocms/plugins#2]
If you have localization enabled on the target field, it will always show up. Whether or not the conditional field is checked.

You can reprodouce this by:
1. Creating a new model
2. Add text field with localization disabled
3. Add boolean field with the conditional field addon
4. Everything should now work correctly
5. Go back to the model and enable localization on the text field
6. Now the text field is always shown

**Comment by stefanoverna** [comment]
Will look into it, thanks for the report @Samuel-L

**Comment by Samuel-L** [comment]
Wohoo, it works after 6781780d7f0bc052337e2cd4ee12dd09e47c208a. Thank you.
