### ISSUE TITLE
Shopify plugins — can't add store keys

### ISSUE THREAD

**Issue by callumflack** [datocms/plugins#26]
On a fresh install of the “Shopify product JSON” plugin, I can’t save my Shopify access keys in order to use this plugin.

The "Shopify product JSON" plugin isn't a Dato plugin. So I tried all the other Shopify plugins, and they all give the same error. This includes the official Dato Shopify plugin ("Shopify product").

![image](https://user-images.githubusercontent.com/749885/94756681-850ee880-03db-11eb-9aab-827413096fe9.png)

**Comment by stefanoverna** [comment]
Thanks @callumflack, should be fixed now!
