### ISSUE TITLE
[Conditional Fields] Bug: Not working for fields in modular content blocks

### ISSUE THREAD

**Issue by floristenhove** [datocms/plugins#27]
It looks like the plugin is not working for modular blocks. I'll try to create a PR when I find the time.
In my case there are fields using the same api key but in different modular blocks. I think that has something to do with this issue.

Version: v0.0.12

**Comment by sarahledu** [comment]
Hi ! Could you confirm that the plugin does not work with modular blocks ?

**Comment by marcelofinamorvieira** [comment]
Hello @sarahledu, this is no longer an issue, and you can use conditional fields normally with modular blocks now.
