### ISSUE TITLE
feat: shopify collection plugin

### ISSUE THREAD

**Issue by tmm** [datocms/plugins#30]
Similar to how there is a [plugin for selecting Shopify products](https://github.com/datocms/plugins/tree/master/shopify-product), it would be great if there was one for selecting Shopify colllections.

Are there plans for this? If not, I would be happy to take this on. (Someone else [mentioned](https://github.com/datocms/product-roadmap/issues/85#issuecomment-433551995) this idea a while ago too.)

**Comment by stefanoverna** [comment]
We have no plans to develop it in the near future @tmm, so go right ahead!
