### ISSUE TITLE
Yoast is a protected trademark

### ISSUE THREAD

**Issue by jdevalk** [datocms/plugins#34]
Hi,

Yoast is a protected trademark. Please get in touch with us for a license agreement.

**Comment by stefanoverna** [comment]
We'll immediately rename the plugin into a more generic "SEO Analysis", thanks for the heads up.

**Comment by jdevalk** [comment]
Note that we’re happy to work with you and come up with something mutually beneficial 😀

**Comment by stefanoverna** [comment]
👍🏻 please send a mail to support@datocms.com so that we can continue the discussion
