### ISSUE TITLE
[Commerce layer] Iframe between the title and help text adds extra space

### ISSUE THREAD

**Issue by smalonso** [datocms/plugins#51]
The extension adds an invisible iframe with a height of 35px between the title and the help text. 

![switch](https://user-images.githubusercontent.com/1012141/146048237-3bd8001e-86b9-4413-87c2-71d59d70bf13.png)

**Comment by stefanoverna** [comment]
Hi! The new home for CommerceLayer plugin is this! https://github.com/commercelayer/dato-plugin

A complete overhaul of the plugin is in the works (https://github.com/commercelayer/dato-plugin/pull/1), and this should hopefully be fixed!
