### ISSUE TITLE
Distorted table in case of large number of column

### ISSUE THREAD

**Issue by anshumansworld** [datocms/plugins#56]
Bug for [table-editor](https://github.com/datocms/plugins/tree/master/table-editor#readme) plugin written by @stefanoverna 

The table is not scrollable (even in full-screen mode) if the number of columns is more than 9.

**Comment by stefanoverna** [comment]
Fixed in v0.1.2!

![2022-04-04 10 56 11](https://user-images.githubusercontent.com/51573/161509783-b2baa2ee-58c4-4116-a416-6408a9ec477a.gif)

**Comment by anshumansworld** [comment]
After the above fix, actions on rows are not available. It's because of a CSS issue. I have fixed it in PR https://github.com/datocms/plugins/pull/59.
It's working fine after applying the following CSS changes:
<img width="1004" alt="Screen Shot 2022-07-02 at 2 36 36 PM" src="https://user-images.githubusercontent.com/1582526/176994446-9dee5960-1b1d-4cc8-a0c2-369c6bfaba98.png">

**Comment by anshumansworld** [comment]
@stefanoverna There is some issue. I see following message.
<img width="499" alt="Screen Shot 2022-07-12 at 12 07 42 AM" src="https://user-images.githubusercontent.com/1582526/178335698-ac719634-e7c2-48f5-91a2-b0c1e1feb11d.png">

**Comment by stefanoverna** [comment]
It might have been a temporary downtime of unpkg.com? Could you retry, seems to work here!
