### ISSUE TITLE
Tag Editor: Field focus/scroll jump

### ISSUE THREAD

**Issue by emaddoma** [datocms/plugins#6]
The way the DatoCMS ui scrolls to fields using this plugin is jarring and super annoying.  Please, please fix it.

**Comment by emaddoma** [comment]
[Screen recording](https://imgur.com/a/txG0Dbb)

**Comment by matjack1** [comment]
oh yes, i can reproduce now! Sorry about that, we'll work on it as soon as possible

**Comment by souljuse** [comment]
@emaddoma, fixed on version 0.0.8 of the Tag Editor plugin!
