### ISSUE TITLE
[Table Editor] GraphQL results order

### ISSUE THREAD

**Issue by erik-seifert** [datocms/plugins#60]
First: Nice plugin.

But when i change the table, row are sorted different. 

Table in Editor

| Years | Chrome | Mozilla | Safari |
---------------------------------------------
| 1995 | 100         | 150      | 200    |

Output:
`{Chrome: 100, Mozilla: 150, Safari: 200, Years: 1995}`

**Comment by erik-seifert** [comment]
Could be there:

https://github.com/datocms/plugins/blob/master/table-editor/src/types.ts#L52

**Comment by stefanoverna** [comment]
The output is an hash, where order of properties is not guaranteed. Please use `.columns` to know the correct order to use!
