### ISSUE TITLE
[Table Editor] Renaming a column to empty string crashes the whole table without saving or leaving any warning.

### ISSUE THREAD

**Issue by sayinserdar** [datocms/plugins#62]
https://user-images.githubusercontent.com/26919126/185950734-c2daf460-d743-42e4-b642-a962feb86062.mp4

Hey! As I mentioned in the title whenever we try to rename the column name to an empty string, the table crashes. This bug drastically slows down our content addition/manipulation d. It would be great if this bug was fixed :) Cheers

Edit: Console logs
<img width="963" alt="image" src="https://user-images.githubusercontent.com/26919126/186090312-a6bac81e-4c56-4314-b3a6-66c5485bc195.png">

**Comment by souljuse** [comment]
Closed with version 0.1.4
