### ISSUE TITLE
[Table Editor] There is no way to remove a row altogether.

### ISSUE THREAD

**Issue by sayinserdar** [datocms/plugins#63]
Hi!  When we do extensive data manipulation in Dato, we need to remove a row from the table. To my knowledge, there is no row deletion feature in the plugin at the moment. Is there a plan to add this feature? It would be great if we could remove a row as well as a column.
Cheers

**Comment by souljuse** [comment]
Hi! Can you please provide a screen recording of the issue? 
I am able to delete a row
![](https://user-images.githubusercontent.com/13051823/189373811-6517e2f2-82b6-4588-a364-7c6ecd19a357.gif)

**Comment by sayinserdar** [comment]
I can delete a row now as well 🥳  It must be a rendering bug then. I wasn't even able to see the leftmost greyed column. Thanks for being responsive.
