### ISSUE TITLE
Conditional Fields: non-exposure warning when used twice on a field

### ISSUE THREAD

**Issue by colinhowells** [datocms/plugins#66]
I have Conditional Fields on a boolean, and while the plugin works fine, there's a perpetual error:

```
ADD-ON MISSING!
The Conditional fields plugin is not exposing the add-on "conditionalFields" anymore. Please remove this addon or consult the plugin author to sort this out!
```

Since I can't hide fields by default, I need to be able to hide some fields _and_ show others, and I think the only way I can do that is by using the plugin twice on a field (seen below) and that's triggering the error – though the plugin does what I need it to do despite it.

I think, given that the plugin still works, this use case could be accommodated? Or maybe the UI of it could be revised so that showing and hiding could be done in one operation.

![conditionalFields](https://user-images.githubusercontent.com/2035314/193944671-1fcdfb24-e7c2-403b-bb07-119f1933c758.jpg)

**Comment by stefanoverna** [comment]
Could you please provide your DatoCMS project ID, and the ID of the field where this is happening? Thanks!

**Comment by colinhowells** [comment]
Sure – project 66134, primary env field 4555336

**Comment by stefanoverna** [comment]
Should be fixed now! Thanks for reporting @colinhowells! :)

**Comment by colinhowells** [comment]
Many thanks!
