### ISSUE TITLE
[Table] Renaming a Column will change the order of properties in object

### ISSUE THREAD

**Issue by jordykoppen** [datocms/plugins#67]
Hey, I'm running into a bug in production concerning the Table plugin:

Whenever I rename a column, the order of the data being returned by Dato API changes. 

Example Table:
| Column A | Column B | Column C |
|----------|----------|----------|
| Value 1  | Value 2  | Value 3  |

API returns:
```json
{
  "columns": [
    "Column A",
    "Column B",
    "Column C"
  ],
  "data": [
    {
      "Column A": "Value 1",
      "Column B": "Value 2",
      "Column C": "Value 3"
    }
  ]
}
```

However, if we rename `Column B` to `Column B2` through the Table Editor, the API result will be:
```json
{
  "columns": [
    "Column A",
    "Column B",
    "Column C"
  ],
  "data": [
    {
      "Column A": "Value 1",
      "Column C": "Value 3",
      "Column B2": "Value 2"
    }
  ]
}
```

**Comment by stefanoverna** [comment]
Fixed in the latest version of the plugin, please upgrade! :)
