### ISSUE TITLE
Table block bugs out if you add a column to the left side of the first column 

### ISSUE THREAD

**Issue by Dsalinasgardon** [datocms/plugins#69]
it seems that the Table block (in blog posts. It's a Dato plugin) bugs out if you add a column to the left side of the first column (the order of the items gets reversed for some reason, it's something to do with the plugin I think.

**Comment by aatu-ikius** [comment]
Referring to [this](https://github.com/datocms/plugins/tree/master/table-editor) plugin

**Comment by stefanoverna** [comment]
@Dsalinasgardon could you paste a GIF with the issue, I cannot reproduce it :/

**Comment by stefanoverna** [comment]
Closing for now, feel free to re-open!

**Comment by aatu-ikius** [comment]
@stefanoverna yes, this seems to have been a duplicate of #67. Thanks!
