### ISSUE TITLE
Conditional fields - implement inverted relationships

### ISSUE THREAD

**Issue by GordanRatkovic** [datocms/plugins#7]
Right now, a slave field is shown when the master boolean field is set to `true`, and hidden when it's `false`

Would be great to be able to define inverted relationships, for example: show slave field when master boolean is `false` (and vice versa).

Perhaps you could just supply the field api key, prefixed with a `!`, for example: `!github, facebook, !twitter`

**Comment by matjack1** [comment]
hello @GordanRatkovic I'm moving this feature request here: https://community.datocms.com/t/conditional-fields-implement-inverted-relationships/448

as otherwise it will never get the due attention :)

Please follow up there, thank you for this!
