### ISSUE TITLE
Character Counter plugin "duplicate"?

### ISSUE THREAD

**Issue by jbmoelker** [datocms/plugins#72]
Hi @stefanoverna, there's already a Word Counter plugin by @velomovies that includes the character counter functionality. Maybe we should try and merge the two?

**Comment by stefanoverna** [comment]
Hi! Sure! We released this plugin just to expose exactly the same tiny counter functionality that was available by default on DatoCMS when some length validation was present on a field, and has recently been removed from core. 

Your plugin is much more configurable! The only thing that maybe is missing is an option to show the counters only if there is some length validation on the field itself, and the fact that when collapsed you can only see the word counter (and not ie. the character count), regardless of the settings :)

I think it's fair for us to offer a plugin that reproduces exactly the old behavior that was available in the core... but maybe we can specify in the README that if they want something more advanced, then they can install Word Counter? 😕 

I'm just snowballing ideas here feel free to give your opinion!

**Comment by stefanoverna** [comment]
Another option: we could use some of our @marcelofinamorvieira's time to write a PR on your Word Counter plugin to add a couple of options for what's missing, and maybe then deprecate ours?

**Comment by matjack1** [comment]
hey @jbmoelker I'm closing this for now, but if you are interested again let us know! :)
