### ISSUE TITLE
[Table Editor] Support for links

### ISSUE THREAD

**Issue by sayinserdar** [datocms/plugins#74]
Hey there, we've been using table editor for a while and we have an occurring need from the plugin. We want to be able to add links to the table content.

There are possible solutions to this, here are some we thought of.
1. Structured Text syntax
<img width="141" alt="image" src="https://user-images.githubusercontent.com/26919126/205876911-1f6d76ee-d71e-4a7e-a592-ba1869828927.png">
2. Html Editor syntax
<img width="547" alt="image" src="https://user-images.githubusercontent.com/26919126/205877079-91fdb9c0-ed45-4ca8-a403-893325fc126e.png">

Currently, we are overcoming this issue by using the Markdown syntax but it's very error prone and it's focused on manual parsing.

As in 
```[Duck Duck Go](https://duckduckgo.com)```
My favorite search engine is [Duck Duck Go](https://duckduckgo.com).

Is there a plan to add link support to the table plugin? If not do you have any suggestions?
Cheers

**Comment by matjack1** [comment]
We have a feature request open for this here: https://community.datocms.com/t/html-table-in-structured-text/2477/12

Please upvote that and I'm closing this to avoid duplication, thanks!
