### ISSUE TITLE
[Shopify Product] strange API issues

### ISSUE THREAD

**Issue by colinhowells** [datocms/plugins#80]
Not sure what's going on but the Shopify Product plugin (v. 0.1.4)
- reports Storefront API tokens not being for the domain when they are ('The API key seems to be invalid for the specified Shopify domain!')
- fail to fetch product data either completely ('API call failed!' on initialization) or partially, so some products cannot be found while others are (this one is really weird)

I've tested the same queries and tokens with API clients, and the keys I'd like to use are fine (they're actually active elsewhere doing much the same thing the plugins are, with no problems). I've also double-checked the permissions those tokens have, and they're what the plugin asks for.

Things were working up to a few days ago – and the problem seems to be limited exclusively to Dato, I can't reproduce the issues anywhere else (is Shopify rate-limiting hits from the Dato domain? Do we need a specific api version called within the plugin now?). 

Right now I've gotten rid of the plugins, and instead having editors input product handles by hand, which is a much less fun experience but at least I know that'll work (as long as the handle exists).

I wish I had more info for you, but there are no errors logged to console that I could send. If you need any information let me know, and if anyone else is having the same troubles.

**Comment by colinhowells** [comment]
I think the case of the plugin not being able to read the entire product catalog may be due to that particular app not having access to the entire catalog ... 

But we do have apps which can read everything, whose tokens are in use successfully elsewhere, which the plugin reports can't be used on the subdomain.

**Comment by souljuse** [comment]
Hi @colinhowells! We fixed the bug in version 0.1.5, thanks for reporting this
