### ISSUE TITLE
[Table] Cursor jumps back and forward whilst editing cell values

### ISSUE THREAD

**Issue by jordykoppen** [datocms/plugins#81]
Hello! One of our content editors reported a bug with the table editor plugin:

Whenever we try to edit a cell's existing value, the cursor randomly goes to the end of the line:

https://user-images.githubusercontent.com/24296556/228824786-25caac59-a7db-466d-9a1c-5692667d0d93.mp4

Please let me know if you need anymore information! 😄

**Comment by matjack1** [comment]
yes, sure, we'll have a look!

**Comment by sistrall** [comment]
Hi @ellenblq :-)

nice to meet you.

Please provide some context to the issue reported: it would help to know which browser you're using and if you have any particular extension enabled (it looks like you're using Grammarly, but maybe there are others). What operating system are you using? Does the problem happens for every cell or did you notice some pattern?

It could help to have a check using an incognito window: in that case, extensions should be disabled.

Thanks!

**Comment by jordykoppen** [comment]
Hi @sistrall

In the video, I was using Chrome on MacOS with Grammarly enabled. I just checked whether Grammarly was the issue but the issue still persists without Grammarly, or other extensions enabled in incognito.

No patterns, just whenever editing a cell.

Thanks!

**Comment by sistrall** [comment]
@jordykoppen @ellenblq plugin version 1.0.8 fixes the problem. :-)

**Comment by jordykoppen** [comment]
Can confirm. Thanks a lot! 😄
