### ISSUE TITLE
SEO/Readability Analysis plugin not doing anything 

### ISSUE THREAD

**Issue by faisal212** [datocms/plugins#83]
The Yoast SEO section is not visible on the content editor page.

These are the steps I took:

    I created an SEO-readability-metadata API endpoint in my Next.js app, which is successfully returning the data in the required fields mentioned in the documentation. The returning object includes the following:

    Locale
    Slug
    Permalink URL
    Title
    Description
    Content

You can check the page at https://blog.decommerce.com/api/seo-readability-metadata?itemId=63145745.
2) I added the frontend metadata endpoint, https://blog.decommerce.com/api/seo-readability-metadata, inside the "Frontend metadata endpoint URL" field to save the settings.

However, even after completing these steps, the Yoast SEO section is still not showing when I go to the content editing page.
![image](https://user-images.githubusercontent.com/18368305/234584433-fbff54d2-4efd-4b27-b8f9-396d6640aa12.png)

**Comment by stefanoverna** [comment]
> This plugin is meant to be used on JSON fields, so please assign it to some JSON fields in in your project.

You need to add a JSON field to this model, and specify "SEO/Readability Analysis" in the Presentation tab.
