### ISSUE TITLE
Add reload button on WebPreviews sidebar panel

### ISSUE THREAD

**Issue by JanStevens** [datocms/plugins#85]
Hi,

The new sidebar panel is awesome but we would like to have a reload button on it. Not everyone manages to implement the subscribed queries (because of complexity) so it would be handy to have a button that allows a content editor to reload the preview window.

Thanks!

**Comment by stefanoverna** [comment]
That makes sense! We'll add it tomorrow :)

**Comment by JanStevens** [comment]
@stefanoverna I've updated to the latest version but I'm not seeing any changes. If I look at the commit I only see some cosmetic changes 🤔  https://github.com/datocms/plugins/commit/7e1d159223b50b7fe60f966c3cc80a914531b652

![Screenshot 2023-05-11 at 08 41 42](https://github.com/datocms/plugins/assets/1540483/ad47311e-b24f-48d2-8b92-c1eb946170d3)
