### ISSUE TITLE
[Web Previews] Hide sidebar dropdown option if there are no preview links

### ISSUE THREAD

**Issue by JanStevens** [datocms/plugins#87]
Hi,

If you have a record without preview links, the sidebar dropdown should not be available. The user ends up in an empty / non functional sidebar anyways when clicking on it.

![Screenshot 2023-05-11 at 14 13 31](https://github.com/datocms/plugins/assets/1540483/6ab7e205-f84c-4381-8b4d-46679750bc95)

Not sure if this is directly possible with the current plugin-sdk.

Regards,

**Comment by stefanoverna** [comment]
Yes, this is not possible with the current SDK. I'm going to close this for now!
