### ISSUE TITLE
[Disabled Field] Some fields editors are not disabled when the plugin is toggled on for a field

### ISSUE THREAD

**Issue by Jokinen** [datocms/plugins#91]
Hello,

The Disabled field plugin describes that it can be used with any field:

https://www.datocms.com/marketplace/plugins/i/datocms-plugin-disabled-field

However, it seems that it does not work with some more specific editors like `json` or `boolean_radio_group`.

I was wondering whether these fields not working is an oversight or a decision?

We are 'indexing' some data into Dato in order to have faster fetches and give some extra context to our editors. We'd prefer that this data would only be changed by the scripts that sync data between services and were considering the disabled field as an option for doing that.

**Comment by marcelofinamorvieira** [comment]
Hello @Jokinen

We just shipped a fix for this,
Thank you for the feedback!

Let us know if you run into any other issues :)
